### ISSUE TITLE
paper for reference.

### ISSUE THREAD

**Issue by qfhyy** [Yigit-Kuyu/RL-Based-Controller#14]
Hello, this is a very good project. I would like to ask if there is a corresponding paper for reference.

**Comment by Yigit-Kuyu** [comment]
There is no paper, this was for a private research project.

**Comment by qfhyy** [comment]
OK，thanks for your reply.


| |
gyh710437767
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/20/2024 04:54 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Yigit-Kuyu/RL-Based-Controller] paper for reference. (Issue #14) |

There is no paper, this was for a private research project.
